-keep class com.umbra.hooks.MainHook { *; }
-keep class com.umbra.hooks.apps.** { *; }
-keep class com.umbra.hooks.utils.** { *; }
-keep class de.robv.android.xposed.** { *; }
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable
-repackageclasses ''
-allowaccessmodification
-keep class org.luckypray.dexkit.** { *; }
-dontwarn org.luckypray.dexkit.**