-keep class com.my.pinteresthook.MainHook { *; }
-keep class com.my.pinteresthook.AdSanitizer { *; }
-keep class de.robv.android.xposed.** { *; }
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable
-repackageclasses ''
-allowaccessmodification
